#!/bin/bash

log_time=`date +"%Y-%m-%d %H:%M"`
script_name=`basename "$0"`
log_message="$log_time [$script_name]"

trace_stdout=$(traceroute 8.8.8.8)
trace_last_ln="${trace_stdout##*$'\n'}"

if [[ "$trace_last_ln" == "30  * * *" ]]; then
    echo $log_message
    echo "$trace_stdout"
fi
