#!/bin/bash

log_time=`date +"%Y-%m-%d %H:%M"`
script_name=`basename "$0"`
log_message="$log_time [$script_name]"

vcgencmd_temp=`vcgencmd measure_temp | grep -o [^=]*$`

log_message="$log_message $vcgencmd_temp"
echo $log_message
